// components/TrainerSidebar.tsx
'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

export default function TrainerSidebar() {
    const pathname = usePathname();

    const getLinkClass = (href: string) => {
        const isActive = pathname === href;
        if (isActive) {
            return "flex items-center gap-2.5 text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20 py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all duration-150";
        }
        return "flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all";
    };

    return (
        <nav className="bg-surface-container-low dark:bg-surface-container-lowest h-screen w-60 fixed left-0 top-0 hidden md:flex flex-col py-6 px-3 gap-1.5 z-40 flat no shadows border-r border-outline-variant/20">
            <div className="mb-6 px-2.5">
                <Link href="/" className="text-primary block whitespace-nowrap font-bold hover:opacity-85 transition-opacity" style={{ fontFamily: "'Inter', sans-serif", fontSize: "13px", letterSpacing: "0.15em", textTransform: "uppercase" }}>
                    Lemon Academy
                </Link>
                <p className="text-[9px] text-on-surface-variant mt-0.5 tracking-wider uppercase" style={{ fontFamily: "'Inter', sans-serif" }}>Trainer Portal</p>
            </div>
            <ul className="flex flex-col gap-1 flex-grow">
                <li>
                    <Link className={getLinkClass('/trainer/dashboard')} href="/trainer/dashboard">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="dashboard">dashboard</span>
                        Dashboard
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/trainer/courses')} href="/trainer/courses">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="school">school</span>
                        My Courses
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/trainer/students')} href="/trainer/students">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="group">group</span>
                        Students
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/trainer/classes')} href="/trainer/classes">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="video_camera_front">video_camera_front</span>
                        Live Classes
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/trainer/resources')} href="/trainer/resources">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="folder">folder</span>
                        Resources
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/trainer/blogs')} href="/trainer/blogs">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="article">article</span>
                        Blogs
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/trainer/gallery')} href="/trainer/gallery">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="image">image</span>
                        Gallery
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/trainer/profile')} href="/trainer/profile">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="person">person</span>
                        Profile
                    </Link>
                </li>
            </ul>
            <div className="mt-auto px-2.5">
                <button 
                    onClick={() => {
                        const deleteCookie = (name: string) => {
                            document.cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;`;
                        };
                        localStorage.removeItem('is_logged_in');
                        localStorage.removeItem('user_role');
                        localStorage.removeItem('user_email');
                        localStorage.removeItem('user_name');
                        localStorage.removeItem('auth_token');
                        deleteCookie('is_logged_in');
                        deleteCookie('user_role');
                        deleteCookie('user_email');
                        deleteCookie('user_name');
                        deleteCookie('auth_token');
                        window.dispatchEvent(new Event('auth_state_changed'));
                        window.location.href = '/';
                    }}
                    className="w-full text-center bg-surface-container-highest text-on-surface font-semibold text-[13px] py-2 rounded-md hover:bg-surface-variant transition-colors shadow-sm"
                >
                    Logout
                </button>
                <div className="flex items-center gap-2.5 mt-4 pt-3 border-t border-outline-variant/30">
                    <div className="w-8 h-8 rounded-full bg-secondary-container text-on-secondary-container flex items-center justify-center font-bold text-xs">
                        E
                    </div>
                    <div className="flex flex-col">
                        <span className="font-semibold text-xs text-on-surface">Elena Cruz</span>
                        <span className="text-[10px] text-on-surface-variant truncate max-w-[120px]">elena@lemon.edu</span>
                    </div>
                </div>
            </div>
        </nav>
    );
}

// src/app/shared/components/trainer-sidebar/trainer-sidebar.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-trainer-sidebar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './trainer-sidebar.component.html'
})
export class TrainerSidebarComponent {
  authService = inject(AuthService);

  handleLogout(): void {
    this.authService.logout();
  }
}

<nav class="bg-surface-container-low h-screen w-60 fixed left-0 top-0 hidden md:flex flex-col py-6 px-3 gap-1.5 z-40 flat no shadows border-r border-outline-variant/20">
  <div class="mb-6 px-2.5">
    <a routerLink="/" class="text-primary block whitespace-nowrap font-bold hover:opacity-85 transition-opacity" style="font-family: 'Inter', sans-serif; font-size: 13px; letter-spacing: 0.15em; text-transform: uppercase;">
      Lemon Academy
    </a>
    <p class="text-[9px] text-on-surface-variant mt-0.5 tracking-wider uppercase" style="font-family: 'Inter', sans-serif;">
      Trainer Portal
    </p>
  </div>

  <ul class="flex flex-col gap-1 flex-grow">
    <li>
      <a routerLink="/trainer/dashboard" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">dashboard</span>
        Dashboard
      </a>
    </li>
    <li>
      <a routerLink="/trainer/courses" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">school</span>
        My Courses
      </a>
    </li>
    <li>
      <a routerLink="/trainer/students" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">group</span>
        Students
      </a>
    </li>
    <li>
      <a routerLink="/trainer/classes" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">video_camera_front</span>
        Live Classes
      </a>
    </li>
    <li>
      <a routerLink="/trainer/resources" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">folder</span>
        Resources
      </a>
    </li>
    <li>
      <a routerLink="/trainer/blogs" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">article</span>
        Blogs
      </a>
    </li>
    <li>
      <a routerLink="/trainer/gallery" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">image</span>
        Gallery
      </a>
    </li>
    <li>
      <a routerLink="/trainer/profile" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">person</span>
        Profile
      </a>
    </li>
  </ul>

  <div class="mt-auto px-2.5">
    <button 
      (click)="handleLogout()"
      class="w-full text-center bg-surface-container-highest text-on-surface font-semibold text-[13px] py-2 rounded-md hover:bg-surface-variant transition-colors shadow-sm">
      Logout
    </button>
    <div class="flex items-center gap-2.5 mt-4 pt-3 border-t border-outline-variant/30">
      <div class="w-8 h-8 rounded-full bg-secondary-container text-on-secondary-container flex items-center justify-center font-bold text-xs">
        {{ (authService.userName() || 'Elena').slice(0, 1) }}
      </div>
      <div class="flex flex-col">
        <span class="font-semibold text-xs text-on-surface">{{ authService.userName() || 'Elena Cruz' }}</span>
        <span class="text-[10px] text-on-surface-variant truncate max-w-[120px]">{{ authService.userEmail() || 'elena@lemon.edu' }}</span>
      </div>
    </div>
  </div>
</nav>
