// src/app/features/public/courses/courses.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { CourseService } from '../../../core/services/course.service';
import { Course } from '../../../core/models/course.model';

@Component({
  selector: 'app-courses',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './courses.component.html'
})
export class CoursesComponent implements OnInit {
  private courseService = inject(CourseService);

  courses = signal<Course[]>([]);
  loading = signal<boolean>(true);
  selectedCategories = signal<string[]>([]);
  categories = [
    { name: 'Lippan Art', slug: 'lippan-art' },
    { name: 'Mosaic Art', slug: 'mosaic-art' },
    { name: 'Crochet & Fiber Arts', slug: 'crochet-fiber-arts' },
    { name: 'Resin Art', slug: 'resin-art' },
    { name: 'Pottery', slug: 'pottery' }
  ];

  ngOnInit(): void {
    this.fetchCourses();
  }

  fetchCourses(): void {
    this.loading.set(true);
    this.courseService.getCourses().subscribe({
      next: (data) => {
        this.courses.set(data);
        this.loading.set(false);
      },
      error: () => {
        this.courses.set(this.courseService.getMockCourses());
        this.loading.set(false);
      }
    });
  }

  handleCategoryToggle(slug: string): void {
    this.selectedCategories.update(prev =>
      prev.includes(slug) ? prev.filter(s => s !== slug) : [...prev, slug]
    );
  }

  get filteredCourses(): Course[] {
    const cats = this.selectedCategories();
    if (cats.length === 0) return this.courses();

    return this.courses().filter(course => {
      return cats.includes(course.categorySlug || '') ||
        cats.some(cat => course.category.toLowerCase().includes(cat.toLowerCase()));
    });
  }

  getInitials(name: string): string {
    return (name || 'Guest').split(' ').map(n => n[0]).join('');
  }
}

<main class="flex-grow w-full max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop py-12 text-xs">
  <div class="flex flex-col md:flex-row gap-8">
    <!-- Filters Sidebar -->
    <aside class="w-full md:w-64 flex-shrink-0">
      <div class="sticky top-24 space-y-8 bg-surface-container-low p-6 rounded-xl border border-surface-variant">
        <div>
          <h3 class="font-label-md text-label-md text-on-surface uppercase tracking-widest mb-4 font-bold">Categories</h3>
          <div class="space-y-3">
            @for (cat of categories; track cat.slug) {
              <label class="flex items-center gap-3 cursor-pointer group">
                <input 
                  class="form-checkbox text-primary rounded border-outline-variant focus:ring-primary w-4 h-4 accent-primary" 
                  type="checkbox"
                  [checked]="selectedCategories().includes(cat.slug)"
                  (change)="handleCategoryToggle(cat.slug)"
                />
                <span class="font-body-md text-on-surface-variant group-hover:text-primary transition-colors">
                  {{ cat.name }}
                </span>
              </label>
            }
          </div>
        </div>
        <hr class="border-t border-outline-variant" />
        <div>
          <h3 class="font-label-md text-label-md text-on-surface uppercase tracking-widest mb-4 font-bold">Level</h3>
          <div class="space-y-3">
            @for (level of ['Beginner', 'Intermediate', 'Advanced']; track level) {
              <label class="flex items-center gap-3 cursor-pointer group">
                <input class="form-checkbox text-primary rounded border-outline-variant focus:ring-primary w-4 h-4 accent-primary" type="checkbox" />
                <span class="font-body-md text-on-surface-variant group-hover:text-primary transition-colors">{{ level }}</span>
              </label>
            }
          </div>
        </div>
      </div>
    </aside>

    <!-- Courses Grid Content -->
    <div class="flex-grow">
      <div class="flex justify-between items-center mb-6">
        <span class="font-body-md text-on-surface-variant">
          Showing {{ filteredCourses.length }} creative courses
        </span>
        <select class="bg-surface-container-low border border-outline-variant rounded-md py-1.5 pl-3 pr-8 font-body-md text-on-surface focus:ring-primary focus:border-primary">
          <option>Sort by: Recommended</option>
          <option>Newest</option>
          <option>Price: Low to High</option>
          <option>Price: High to Low</option>
        </select>
      </div>

      @if (loading()) {
        <div class="flex flex-col items-center justify-center py-24 space-y-4 bg-surface-container-lowest border border-outline-variant/30 rounded-2xl p-8 shadow-sm">
          <!-- Premium Spinner with Pulse Glow -->
          <div class="relative flex items-center justify-center">
            <div class="w-12 h-12 border-4 border-primary/20 border-t-primary rounded-full animate-spin"></div>
            <div class="absolute w-12 h-12 rounded-full border border-primary/10 animate-ping"></div>
          </div>
          <div class="text-center space-y-1 max-w-sm">
            <p class="font-bold text-on-surface text-sm">Waking up the backend server...</p>
            <p class="text-[11px] text-on-surface-variant leading-relaxed">
              Our free-tier server takes about 30 seconds to wake up from sleep mode. Thank you for waiting!
            </p>
          </div>
        </div>
      } @else if (filteredCourses.length === 0) {
        <div class="text-center py-16 text-on-surface-variant bg-surface-container-lowest border border-outline-variant/30 rounded-2xl">
          No courses matching the selected filters.
        </div>
      } @else {
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          @for (course of filteredCourses; track course.id) {
            <div class="bg-surface-container-lowest rounded-xl overflow-hidden shadow-sm hover:-translate-y-1 hover:shadow-md transition-all duration-300 group flex flex-col h-full border border-outline-variant/20">
              <div class="relative h-44 overflow-hidden bg-surface-variant">
                <img class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" [alt]="course.title" [src]="course.imageUrl" />
                <div class="absolute top-3 left-3 bg-tertiary-fixed px-2.5 py-0.5 rounded-full text-on-tertiary-fixed text-[10px] font-semibold uppercase tracking-wider">
                  {{ course.category }}
                </div>
              </div>
              <div class="p-5 flex flex-col flex-grow justify-between gap-4">
                <div class="space-y-2">
                  <h3 class="font-bold text-on-surface text-sm leading-snug group-hover:text-primary transition-colors line-clamp-2">
                    <a [routerLink]="course.id === 'lippan-art' ? '/courses/lippan-art' : '/courses'">{{ course.title }}</a>
                  </h3>
                  <p class="text-on-surface-variant line-clamp-2 text-[11px] leading-relaxed">
                    {{ course.description || "Master new artisanal skills from the foundation to intermediate levels." }}
                  </p>
                </div>
                <div class="space-y-3">
                  <div class="flex items-center gap-2">
                    <div class="w-5 h-5 rounded-full bg-secondary-container text-on-secondary-container flex items-center justify-center text-[10px] font-bold">
                      {{ getInitials(course.instructor) }}
                    </div>
                    <span class="text-on-surface-variant font-medium text-[11px]">{{ course.instructor }}</span>
                  </div>
                  <div class="flex justify-between items-center border-t border-surface-variant/45 pt-3">
                    <div class="flex items-center text-primary-fixed-dim">
                      <span class="material-symbols-outlined filled text-xs">star</span>
                      <span class="material-symbols-outlined filled text-xs">star</span>
                      <span class="material-symbols-outlined filled text-xs">star</span>
                      <span class="material-symbols-outlined filled text-xs">star</span>
                      <span class="material-symbols-outlined text-xs">star_half</span>
                      <span class="text-on-surface font-semibold ml-1 text-[10px]">4.8</span>
                      <span class="text-on-surface-variant ml-1 text-[10px]">({{ course.studentsCount }})</span>
                    </div>
                    <div class="text-right">
                      <div class="font-bold text-primary text-sm">Rs. {{ course.price }}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          }
        </div>
      }
    </div>
  </div>
</main>

// app/admin/courses/page.tsx
'use client';
import { useState } from 'react';

interface CourseItem {
    id: number;
    title: string;
    category: string;
    trainer: string;
    price: number;
    studentsCount: number;
    status: 'Published' | 'Draft';
    createdDate: string;
}

export default function AdminCourseManagement() {
    const [courses, setCourses] = useState<CourseItem[]>([]);
    const [isCreating, setIsCreating] = useState(false);
    
    // Form states
    const [title, setTitle] = useState('');
    const [category, setCategory] = useState('');
    const [trainer, setTrainer] = useState('');
    const [price, setPrice] = useState<number>(0);
    const [status, setStatus] = useState<'Published' | 'Draft'>('Draft');

    const handleCreateCourse = (e: React.FormEvent) => {
        e.preventDefault();
        if (!title.trim()) return;

        const newCourse: CourseItem = {
            id: Date.now(),
            title: title.trim(),
            category: category.trim() || 'General Craft',
            trainer: trainer.trim() || 'Guest Instructor',
            price: Number(price),
            studentsCount: 0,
            status,
            createdDate: new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' })
        };

        setCourses([...courses, newCourse]);
        setTitle('');
        setCategory('');
        setTrainer('');
        setPrice(0);
        setIsCreating(false);
    };

    return (
        <main className="flex-grow w-full px-margin-mobile md:px-margin-desktop py-6 max-w-[1440px] mx-auto min-h-screen text-xs">

            <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-6">
                <div>
                    <h2 className="text-xl font-bold text-on-background mb-1">Courses</h2>
                    <p className="text-xs text-on-surface-variant max-w-lg">Manage your creative curriculum. Track enrollments, update syllabi, and publish new artisanal workshops.</p>
                </div>
                <button 
                    onClick={() => setIsCreating(!isCreating)}
                    className="flex items-center gap-1.5 bg-primary text-primary-fixed hover:bg-surface-tint font-semibold text-xs py-2 px-4 rounded-lg transition-colors whitespace-nowrap shadow-sm"
                >
                    <span className="material-symbols-outlined text-[16px]">add</span>
                    {isCreating ? 'Cancel' : 'Create Course'}
                </button>
            </div>

            {isCreating && (
                <div className="bg-surface-container-lowest rounded-xl border border-outline-variant/30 p-4 shadow-sm mb-6 max-w-xl">
                    <h3 className="text-sm font-bold text-on-surface mb-3">Add New Course</h3>
                    <form onSubmit={handleCreateCourse} className="space-y-3">
                        <div>
                            <label className="block font-semibold text-on-surface-variant mb-1">Course Title</label>
                            <input 
                                type="text" 
                                className="w-full bg-surface-container-low border border-outline-variant/40 rounded-lg p-2 focus:ring-1 focus:ring-primary focus:outline-none" 
                                placeholder="e.g. Advanced Pottery Wheel"
                                value={title}
                                onChange={(e) => setTitle(e.target.value)}
                                required
                            />
                        </div>
                        <div className="grid grid-cols-2 gap-2">
                            <div>
                                <label className="block font-semibold text-on-surface-variant mb-1">Category</label>
                                <input 
                                    type="text" 
                                    className="w-full bg-surface-container-low border border-outline-variant/40 rounded-lg p-2 focus:ring-1 focus:ring-primary focus:outline-none" 
                                    placeholder="e.g. Pottery"
                                    value={category}
                                    onChange={(e) => setCategory(e.target.value)}
                                />
                            </div>
                            <div>
                                <label className="block font-semibold text-on-surface-variant mb-1">Trainer Name</label>
                                <input 
                                    type="text" 
                                    className="w-full bg-surface-container-low border border-outline-variant/40 rounded-lg p-2 focus:ring-1 focus:ring-primary focus:outline-none" 
                                    placeholder="e.g. Elena Cruz"
                                    value={trainer}
                                    onChange={(e) => setTrainer(e.target.value)}
                                />
                            </div>
                        </div>
                        <div className="grid grid-cols-2 gap-2">
                            <div>
                                <label className="block font-semibold text-on-surface-variant mb-1">Price (Rs.)</label>
                                <input 
                                    type="number" 
                                    className="w-full bg-surface-container-low border border-outline-variant/40 rounded-lg p-2 focus:ring-1 focus:ring-primary focus:outline-none" 
                                    min={0}
                                    value={price}
                                    onChange={(e) => setPrice(Number(e.target.value))}
                                />
                            </div>
                            <div>
                                <label className="block font-semibold text-on-surface-variant mb-1">Status</label>
                                <select 
                                    className="w-full bg-surface-container-low border border-outline-variant/40 rounded-lg p-2 focus:ring-1 focus:ring-primary focus:outline-none"
                                    value={status}
                                    onChange={(e) => setStatus(e.target.value as any)}
                                >
                                    <option value="Draft">Draft</option>
                                    <option value="Published">Published</option>
                                </select>
                            </div>
                        </div>
                        <button 
                            type="submit" 
                            className="bg-primary text-on-primary font-semibold py-2 px-4 rounded-lg hover:opacity-90 transition-opacity"
                        >
                            Save Course
                        </button>
                    </form>
                </div>
            )}

            <div className="bg-surface-container-lowest rounded-xl shadow-sm border border-outline-variant/30 overflow-hidden">
                <div className="grid grid-cols-12 gap-4 p-4 border-b border-outline-variant bg-surface-container-low/50">
                    <div className="col-span-12 md:col-span-4 text-[10px] font-semibold text-on-surface-variant uppercase tracking-wider">Course</div>
                    <div className="hidden md:block col-span-3 text-[10px] font-semibold text-on-surface-variant uppercase tracking-wider">Trainer</div>
                    <div className="hidden md:block col-span-1 text-[10px] font-semibold text-on-surface-variant uppercase tracking-wider text-right">Price</div>
                    <div className="hidden md:block col-span-1 text-[10px] font-semibold text-on-surface-variant uppercase tracking-wider text-right">Students</div>
                    <div className="hidden md:block col-span-3 text-[10px] font-semibold text-on-surface-variant uppercase tracking-wider text-center">Status</div>
                </div>

                <div className="flex flex-col divide-y divide-outline-variant/20">
                    {courses.map((course) => (
                        <div key={course.id} className="grid grid-cols-12 gap-4 p-4 items-center hover:bg-surface-container-low/30 transition-colors">
                            <div className="col-span-12 md:col-span-4 flex items-center gap-3">
                                <div>
                                    <h3 className="font-bold text-on-background">{course.title}</h3>
                                    <p className="text-[10px] text-on-surface-variant mt-0.5">{course.category}</p>
                                </div>
                            </div>
                            <div className="hidden md:flex col-span-3 items-center gap-2">
                                <span className="text-on-surface">{course.trainer}</span>
                            </div>
                            <div className="hidden md:block col-span-1 text-on-surface text-right font-semibold">Rs. {course.price}</div>
                            <div className="hidden md:block col-span-1 text-on-surface text-right">{course.studentsCount}</div>
                            <div className="hidden md:flex col-span-3 justify-center">
                                <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-semibold ${
                                    course.status === 'Published' 
                                        ? 'bg-tertiary-fixed/40 text-on-tertiary-fixed-variant' 
                                        : 'bg-surface-variant text-on-surface-variant'
                                }`}>
                                    {course.status}
                                </span>
                            </div>
                        </div>
                    ))}
                    {courses.length === 0 && (
                        <div className="py-8 text-center text-on-surface-variant">
                            No courses available. Click "Create Course" to add one.
                        </div>
                    )}
                </div>
            </div>
        </main>
    );
}
