// src/app/shared/components/admin-sidebar/admin-sidebar.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-admin-sidebar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './admin-sidebar.component.html'
})
export class AdminSidebarComponent {
  authService = inject(AuthService);

  handleLogout(): void {
    this.authService.logout();
  }
}

<nav class="bg-surface-container-low h-screen w-60 fixed left-0 top-0 hidden md:flex flex-col py-6 px-3 gap-1.5 z-40 flat no shadows border-r border-outline-variant/20">
  <div class="mb-6 px-2.5">
    <a routerLink="/" class="text-primary block whitespace-nowrap font-bold hover:opacity-85 transition-opacity" style="font-family: 'Inter', sans-serif; font-size: 13px; letter-spacing: 0.15em; text-transform: uppercase;">
      Lemon Academy
    </a>
    <p class="text-[9px] text-on-surface-variant mt-0.5 tracking-wider uppercase" style="font-family: 'Inter', sans-serif;">
      Admin Portal
    </p>
  </div>

  <ul class="flex flex-col gap-1 flex-grow">
    <li>
      <a routerLink="/admin/dashboard" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">dashboard</span>
        Dashboard
      </a>
    </li>
    <li>
      <a routerLink="/admin/courses" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">school</span>
        Course Management
      </a>
    </li>
    <li>
      <a routerLink="/admin/students" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">group</span>
        Student Management
      </a>
    </li>
    <li>
      <a routerLink="/admin/content" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">movie</span>
        Creative Content
      </a>
    </li>
    <li>
      <a routerLink="/admin/applications" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">assignment_ind</span>
        Applications
      </a>
    </li>
    <li>
      <a routerLink="/admin/coupons" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">local_offer</span>
        Coupons
      </a>
    </li>
    <li>
      <a routerLink="/admin/blogs" routerLinkActive="text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20" class="flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all">
        <span class="material-symbols-outlined !text-[18px]">edit_note</span>
        Blog Management
      </a>
    </li>
  </ul>

  <div class="mt-auto px-2.5">
    <button 
      (click)="handleLogout()"
      class="w-full block text-center bg-surface-container-highest text-on-surface font-semibold text-[13px] py-2 rounded-md hover:bg-surface-variant transition-colors shadow-sm">
      Logout
    </button>
    <div class="flex items-center gap-2.5 mt-4 pt-3 border-t border-outline-variant/30">
      <img alt="Admin Profile" class="w-8 h-8 rounded-full object-cover border border-outline-variant/50" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBdMARZrb2FmGq85EbzdDLymFBx4CM6RPUJwMlbg7mZhjYEKggA51VEqhuBNLrTHvSlY5FiVk0fPuv9Linj2Wz37KT-EfMi6zfaBVU1flN4P7ZT-CqUgYE9LaglXkYI-HlpS363LihzWoisz9CPSk9wutzq2UrCWhUoSrNb7nrJjkRXPeGfJQgtksg_e-U8tVE7t2LxAKrWVFOb5jDH_nG0qZcvvSnyWFz3xD3CW9hEBu6dyRxvoVkT"/>
      <div class="flex flex-col">
        <span class="font-semibold text-xs text-on-surface">{{ authService.userName() || 'Admin User' }}</span>
        <span class="text-[10px] text-on-surface-variant truncate max-w-[120px]">{{ authService.userEmail() || 'admin@lemon.edu' }}</span>
      </div>
    </div>
  </div>
</nav>

// components/AdminSidebar.tsx
'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

export default function AdminSidebar() {
    const pathname = usePathname();

    const getLinkClass = (href: string) => {
        const isActive = pathname === href;
        if (isActive) {
            return "flex items-center gap-2.5 text-on-primary-fixed-variant font-semibold border-l-4 border-primary-fixed bg-primary-container/20 py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all duration-150";
        }
        return "flex items-center gap-2.5 text-on-surface-variant py-2 px-3 rounded-r-md text-[13px] hover:bg-surface-variant/50 transition-all";
    };

    return (
        <nav className="bg-surface-container-low dark:bg-surface-container-lowest h-screen w-60 fixed left-0 top-0 hidden md:flex flex-col py-6 px-3 gap-1.5 z-40 flat no shadows border-r border-outline-variant/20">
            <div className="mb-6 px-2.5">
                <Link href="/" className="text-primary block whitespace-nowrap font-bold hover:opacity-85 transition-opacity" style={{ fontFamily: "'Inter', sans-serif", fontSize: "13px", letterSpacing: "0.15em", textTransform: "uppercase" }}>
                    Lemon Academy
                </Link>
                <p className="text-[9px] text-on-surface-variant mt-0.5 tracking-wider uppercase" style={{ fontFamily: "'Inter', sans-serif" }}>Admin Portal</p>
            </div>
            <ul className="flex flex-col gap-1 flex-grow">
                <li>
                    <Link className={getLinkClass('/admin/dashboard')} href="/admin/dashboard">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="dashboard">dashboard</span>
                        Dashboard
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/admin/courses')} href="/admin/courses">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="school">school</span>
                        Course Management
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/admin/students')} href="/admin/students">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="group">group</span>
                        Student Management
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/admin/content')} href="/admin/content">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="movie">movie</span>
                        Creative Content
                    </Link>
                </li>

                <li>
                    <Link className={getLinkClass('/admin/applications')} href="/admin/applications">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="assignment_ind">assignment_ind</span>
                        Applications
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/admin/coupons')} href="/admin/coupons">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="local_offer">local_offer</span>
                        Coupons
                    </Link>
                </li>
                <li>
                    <Link className={getLinkClass('/admin/blogs')} href="/admin/blogs">
                        <span className="material-symbols-outlined !text-[18px]" data-icon="edit_note">edit_note</span>
                        Blog Management
                    </Link>
                </li>
            </ul>
            <div className="mt-auto px-2.5">
                <Link href="/login" className="w-full block text-center bg-surface-container-highest text-on-surface font-semibold text-[13px] py-2 rounded-md hover:bg-surface-variant transition-colors shadow-sm">
                    Logout
                </Link>
                <div className="flex items-center gap-2.5 mt-4 pt-3 border-t border-outline-variant/30">
                    <img alt="Admin Profile" className="w-8 h-8 rounded-full object-cover border border-outline-variant/50" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBdMARZrb2FmGq85EbzdDLymFBx4CM6RPUJwMlbg7mZhjYEKggA51VEqhuBNLrTHvSlY5FiVk0fPuv9Linj2Wz37KT-EfMi6zfaBVU1flN4P7ZT-CqUgYE9LaglXkYI-HlpS363LihzWoisz9CPSk9wutzq2UrCWhUoSrNb7nrJjkRXPeGfJQgtksg_e-U8tVE7t2LxAKrWVFOb5jDH_nG0qZcvvSnyWFz3xD3CW9hEBu6dyRxvoVkT"/>
                    <div className="flex flex-col">
                        <span className="font-semibold text-xs text-on-surface">Admin User</span>
                        <span className="text-[10px] text-on-surface-variant truncate max-w-[120px]">admin@lemon.edu</span>
                    </div>
                </div>
            </div>
        </nav>
    );
}
