// app/admin/blogs/page.tsx
'use client';

import { useState, useEffect } from 'react';

interface BlogPost {
    id: number;
    title: string;
    excerpt: string;
    category: string;
    categoryColor: string;
    image: string;
    date: string;
    author: string;
    readTime: string;
    isCustom?: boolean;
}

const CATEGORY_COLORS: { [key: string]: string } = {
    "Crafting Tips": "bg-primary-container text-on-primary-container",
    "Materials Guide": "bg-tertiary-fixed text-on-tertiary-fixed",
    "Artisan Spotlight": "bg-secondary-fixed text-on-secondary-fixed",
    "Community": "bg-surface-variant text-on-surface-variant",
};

const DEFAULT_POSTS: BlogPost[] = [
    {
        id: 1,
        title: "10 Essential Tools for Lippan Art Beginners",
        excerpt: "Discover the must-have tools, mud pastes, and mirrors to start your journey into the beautiful world of traditional Gujarati Lippan Art without making mess.",
        category: "Crafting Tips",
        categoryColor: "bg-primary-container text-on-primary-container",
        image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=600",
        date: "Aug 10, 2026",
        author: "Meera Nair",
        readTime: "5 min read"
    },
    {
        id: 2,
        title: "The Alchemy of Resin: Mastering Curing & Micro-bubbles",
        excerpt: "Tired of cloudy finishes and pesky air pockets? Our master artisan breaks down room temperature control and pouring heights for crystal clear pours.",
        category: "Materials Guide",
        categoryColor: "bg-tertiary-fixed text-on-tertiary-fixed",
        image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=600",
        date: "Aug 06, 2026",
        author: "Vikram Sharma",
        readTime: "7 min read"
    }
];

export default function AdminBlogManagement() {
    const [posts, setPosts] = useState<BlogPost[]>([]);
    const [isWriting, setIsWriting] = useState(false);

    // Form inputs
    const [title, setTitle] = useState('');
    const [excerpt, setExcerpt] = useState('');
    const [category, setCategory] = useState('Crafting Tips');
    const [image, setImage] = useState('https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=600');
    const [author, setAuthor] = useState('Admin User');
    const [readTime, setReadTime] = useState('5 min read');

    const loadPosts = () => {
        const customBlogs = localStorage.getItem('custom_blogs');
        const parsedCustom = customBlogs ? JSON.parse(customBlogs) : [];
        setPosts([...parsedCustom, ...DEFAULT_POSTS]);
    };

    useEffect(() => {
        loadPosts();
    }, []);

    const handleCreatePost = (e: React.FormEvent) => {
        e.preventDefault();
        
        const newPost: BlogPost = {
            id: Date.now(), // Unique ID
            title,
            excerpt,
            category,
            categoryColor: CATEGORY_COLORS[category] || "bg-surface-variant text-on-surface-variant",
            image,
            date: new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }),
            author,
            readTime,
            isCustom: true
        };

        const customBlogs = localStorage.getItem('custom_blogs');
        const parsedCustom = customBlogs ? JSON.parse(customBlogs) : [];
        const updatedCustom = [newPost, ...parsedCustom];
        
        localStorage.setItem('custom_blogs', JSON.stringify(updatedCustom));
        
        // Reset states
        setTitle('');
        setExcerpt('');
        setIsWriting(false);
        
        // Reload list
        loadPosts();
    };

    const handleDeletePost = (id: number) => {
        const customBlogs = localStorage.getItem('custom_blogs');
        if (customBlogs) {
            const parsedCustom = JSON.parse(customBlogs);
            const filtered = parsedCustom.filter((post: BlogPost) => post.id !== id);
            localStorage.setItem('custom_blogs', JSON.stringify(filtered));
        }
        loadPosts();
    };

    return (
        <main className="flex-1 w-full px-margin-mobile md:px-margin-desktop py-6 max-w-[1440px] mx-auto min-h-screen text-on-surface">
            
            <header className="mb-8 border-b border-outline-variant/30 pb-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-on-surface playfair">Blog Management</h1>
                    <p className="text-xs text-on-surface-variant mt-1">
                        Write and edit educational articles, craft guides, and artisan spotlight features for the Lemon Academy stories portal.
                    </p>
                </div>
                <button
                    onClick={() => setIsWriting(!isWriting)}
                    className="self-start sm:self-center bg-primary hover:bg-primary/95 text-white font-bold py-2.5 px-5 rounded-xl transition-all shadow-sm text-xs tracking-wider uppercase flex items-center gap-2"
                >
                    <span className="material-symbols-outlined text-sm">
                        {isWriting ? 'close' : 'edit_note'}
                    </span>
                    {isWriting ? 'Cancel Writing' : 'Write New Article'}
                </button>
            </header>

            {isWriting && (
                <section className="bg-surface-container-low border border-outline-variant/30 rounded-3xl p-6 mb-8 max-w-3xl mx-auto shadow-sm">
                    <h3 className="font-bold text-lg text-on-surface mb-6 flex items-center gap-2">
                        <span className="material-symbols-outlined text-primary">edit_note</span>
                        Write a New Article
                    </h3>
                    
                    <form onSubmit={handleCreatePost} className="space-y-5">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                            <div className="space-y-1.5 col-span-1 md:col-span-2">
                                <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider">
                                    Article Title
                                </label>
                                <input
                                    type="text"
                                    required
                                    value={title}
                                    onChange={(e) => setTitle(e.target.value)}
                                    placeholder="e.g. 5 Simple Steps to Scented Wax Mixing"
                                    className="w-full px-4 py-2.5 rounded-xl bg-surface-container-lowest border border-outline-variant/30 focus:border-primary focus:outline-none transition-all text-sm"
                                />
                            </div>

                            <div className="space-y-1.5 col-span-1 md:col-span-2">
                                <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider">
                                    Excerpt / Subtitle
                                </label>
                                <textarea
                                    required
                                    rows={2}
                                    value={excerpt}
                                    onChange={(e) => setExcerpt(e.target.value)}
                                    placeholder="Provide a brief summary of what this article covers..."
                                    className="w-full px-4 py-2.5 rounded-xl bg-surface-container-lowest border border-outline-variant/30 focus:border-primary focus:outline-none transition-all text-sm resize-none"
                                />
                            </div>

                            <div className="space-y-1.5">
                                <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider">
                                    Category
                                </label>
                                <select
                                    value={category}
                                    onChange={(e) => setCategory(e.target.value)}
                                    className="w-full px-4 py-2.5 rounded-xl bg-surface-container-lowest border border-outline-variant/30 focus:border-primary focus:outline-none transition-all text-sm"
                                >
                                    <option value="Crafting Tips">Crafting Tips</option>
                                    <option value="Materials Guide">Materials Guide</option>
                                    <option value="Artisan Spotlight">Artisan Spotlight</option>
                                    <option value="Community">Community</option>
                                </select>
                            </div>

                            <div className="space-y-1.5">
                                <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider">
                                    Cover Image URL
                                </label>
                                <input
                                    type="text"
                                    required
                                    value={image}
                                    onChange={(e) => setImage(e.target.value)}
                                    className="w-full px-4 py-2.5 rounded-xl bg-surface-container-lowest border border-outline-variant/30 focus:border-primary focus:outline-none transition-all text-sm"
                                />
                            </div>

                            <div className="space-y-1.5">
                                <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider">
                                    Author Name
                                </label>
                                <input
                                    type="text"
                                    required
                                    value={author}
                                    onChange={(e) => setAuthor(e.target.value)}
                                    className="w-full px-4 py-2.5 rounded-xl bg-surface-container-lowest border border-outline-variant/30 focus:border-primary focus:outline-none transition-all text-sm"
                                />
                            </div>

                            <div className="space-y-1.5">
                                <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider">
                                    Estimated Read Time
                                </label>
                                <input
                                    type="text"
                                    required
                                    value={readTime}
                                    onChange={(e) => setReadTime(e.target.value)}
                                    placeholder="e.g. 5 min read"
                                    className="w-full px-4 py-2.5 rounded-xl bg-surface-container-lowest border border-outline-variant/30 focus:border-primary focus:outline-none transition-all text-sm"
                                />
                            </div>
                        </div>

                        <button
                            type="submit"
                            className="w-full bg-primary hover:bg-primary/95 text-white font-bold py-3 px-6 rounded-xl transition-all shadow-sm hover:shadow text-xs tracking-wider uppercase mt-4 flex items-center justify-center gap-2"
                        >
                            Publish Article
                            <span className="material-symbols-outlined text-sm">publish</span>
                        </button>
                    </form>
                </section>
            )}

            {/* Existing Articles List */}
            <section className="bg-surface-container-lowest border border-outline-variant/20 rounded-3xl p-6 shadow-sm">
                <h3 className="font-bold text-lg text-on-surface mb-6">Published Articles</h3>
                
                {posts.length > 0 ? (
                    <div className="overflow-x-auto">
                        <table className="w-full text-left text-sm border-collapse">
                            <thead>
                                <tr className="border-b border-outline-variant/30 text-on-surface-variant font-bold text-xs uppercase tracking-wider">
                                    <th className="py-4 px-4">Article</th>
                                    <th className="py-4 px-4">Category</th>
                                    <th className="py-4 px-4">Author / Date</th>
                                    <th className="py-4 px-4 text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-outline-variant/10">
                                {posts.map((post) => (
                                    <tr key={post.id} className="hover:bg-surface-container-low/20 transition-colors">
                                        <td className="py-4 px-4 flex items-center gap-3">
                                            <img
                                                src={post.image}
                                                alt={post.title}
                                                className="w-12 h-12 rounded-lg object-cover border border-outline-variant/20 shrink-0"
                                            />
                                            <div>
                                                <h4 className="font-bold text-on-surface line-clamp-1">{post.title}</h4>
                                                <p className="text-xs text-on-surface-variant line-clamp-1 mt-0.5">{post.excerpt}</p>
                                            </div>
                                        </td>
                                        <td className="py-4 px-4">
                                            <span className={`inline-block px-3 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${post.categoryColor}`}>
                                                {post.category}
                                            </span>
                                        </td>
                                        <td className="py-4 px-4">
                                            <span className="block font-semibold text-xs text-on-surface">{post.author}</span>
                                            <span className="text-[10px] text-on-surface-variant">{post.date} • {post.readTime}</span>
                                        </td>
                                        <td className="py-4 px-4 text-right">
                                            {post.isCustom ? (
                                                <button
                                                    onClick={() => handleDeletePost(post.id)}
                                                    className="p-2 text-outline hover:text-error hover:bg-error-container/20 rounded-xl transition-all"
                                                    title="Delete Article"
                                                >
                                                    <span className="material-symbols-outlined text-[18px]">delete</span>
                                                </button>
                                            ) : (
                                                <span className="text-[10px] text-outline font-semibold tracking-wide uppercase px-2 py-1 bg-surface-container rounded">
                                                    Static / Core
                                                </span>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                ) : (
                    <div className="text-center py-12 text-on-surface-variant">
                        <span className="material-symbols-outlined text-4xl mb-2 text-outline-variant">find_in_page</span>
                        <p className="text-xs font-semibold">No articles published yet.</p>
                    </div>
                )}
            </section>
        </main>
    );
}

// src/app/features/public/blogs/blogs.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';

interface BlogPost {
  id: number;
  title: string;
  excerpt: string;
  category: string;
  categoryColor: string;
  image: string;
  date: string;
  author: string;
  readTime: string;
}

const ALL_POSTS: BlogPost[] = [
  {
    id: 1,
    title: "10 Essential Tools for Lippan Art Beginners",
    excerpt: "Discover the must-have tools, mud pastes, and mirrors to start your journey into the beautiful world of traditional Gujarati Lippan Art without making mess.",
    category: "Crafting Tips",
    categoryColor: "bg-primary-container text-on-primary-container",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDXiQLIEpsHtGrZbryHVG2dOarl_iT9qvnszntbv8Io-HDvulcLxdeW-m1Y1LvLsZVTdyll6k3sqZuLN0jnUa8PmjFtQMe1mAq8CIzvCN0yaT2ObdUfIPU2XuH0CbkJ-ZzjHMPf30gtRgX14D6XM6dRo4nkeus9cqsp61icBWZjJAhChFKP93gBX9kTPkDU0dKVth2hhMx3C1QEtY_8tkNWkbpTpJ4ASJfAgMhyr-lLHkbEwd9CJP6X",
    date: "Aug 10, 2026",
    author: "Meera Nair",
    readTime: "5 min read"
  },
  {
    id: 2,
    title: "The Alchemy of Resin: Mastering Curing & Micro-bubbles",
    excerpt: "Tired of cloudy finishes and pesky air pockets? Our master artisan breaks down room temperature control and pouring heights for crystal clear pours.",
    category: "Materials Guide",
    categoryColor: "bg-tertiary-fixed text-on-tertiary-fixed",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBy_buYnpjKfjRTyIf3XQ4SNX1F_mcq0L-hg4lny14eYJzf7Bwtuw91_n-0PsBT2hdqKBiZtqfHvzPj8K79SpzOVcuH5lJ_Xb-i3oORdHHh0430xLqp6qhligPWzFUjk3vxgs_KF2PiRX-2JQr6LN72XOGb2W66Jx5LwPzy0T88fGx-weg-dtLvZD2SSLhMeqlXDcYntk9dU5uzP_LtGzwyDBovKAk0lHVbByounJVN03xW3d__NxPA",
    date: "Aug 06, 2026",
    author: "Vikram Sharma",
    readTime: "7 min read"
  },
  {
    id: 3,
    title: "Sourcing Organic Earth Clay: What EdTech Won't Tell You",
    excerpt: "Understanding the difference between terracotta, porcelain, and local riversides clay when building structural forms that do not crack during air drying.",
    category: "Materials Guide",
    categoryColor: "bg-tertiary-fixed text-on-tertiary-fixed",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDCbTN-TaIudH0njCO5lQnLDpdjSBXonaHMG6x1kUfR2uXaU3Bxee-QSSCUKc_3hc1bwYbqoLL7NkuUAWEXphMhqlZj0UGrH5JKFEqWwuvMewqe0IKttUMNPvDyYvT5VOu5OOT2KLk9GRoWqhQtsYqopj7EjtbduvEldGGe5ADkeQ1K066OVltHrOz2DqpUwcxBAwAUGd1pxzDFD-4yEZpe1-WiuoFTNUcsLqLOtiHOQTnGcvfWTkEy",
    date: "Jul 28, 2026",
    author: "Devendra Joshi",
    readTime: "6 min read"
  },
  {
    id: 4,
    title: "Preserving Heritage: Clay Art in Kutch Communities",
    excerpt: "An intimate interview with village women practicing Lippan work on bhungas, keeping a 500-year-old tradition alive in the Rann of Kutch.",
    category: "Artisan Spotlight",
    categoryColor: "bg-secondary-fixed text-on-secondary-fixed",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPiWCQJI93PXDk9BOTIapmtikie4-YaxmLh1RRYduOa_TDE4AQZkdf8DEkTVGR5nS9OSCOgXvKuV_YYJl7XOPbMsOJ2NapTo5sBgHWGuqHmqZjabmFElFjDdYfpq8LsUXrV3nz9yX7Abr5E1fWw9PM_lVq-u8188AjgPz0txpaTpIy1QYYWuyXi3IwoSn_vw542oHbUWJhQ2iOxYf0kpLG7nJ1g6ftWcf9R78bsl9rLf2ndCoywsoF",
    date: "Jul 15, 2026",
    author: "Asha Devi",
    readTime: "8 min read"
  },
  {
    id: 5,
    title: "Why Artisanal Candle Wax selection is Crucial for Scent Throw",
    excerpt: "Evaluating soy, beeswax, and coconut wax blends for clean burning, strong scent throw, and a flawless smooth top surface post-pour.",
    category: "Crafting Tips",
    categoryColor: "bg-primary-container text-on-primary-container",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAdWftkk77PEWsXT0X8Idf_5qfShUey9va1f3wum-E0_wQoJNhH8DlzGO1jy22TTPACpLEnQy1abVm1vhUtDsMA62pD83tLRBO8N6-irLAYagp8jz-xagrBPejAcQrBrwZzDiv9yycKXiyMImwz2fXE8Ti75v-LV1oM7TZC1DEpm5zIscCEoA4rnAVGfQcAfxeIOZaJ1Y7It8VGiYZDtwrBh2OS8uEZ9TL5ABRz7RQ6Rwxmr6C65H3E",
    date: "Jul 09, 2026",
    author: "Karan Johar",
    readTime: "4 min read"
  },
  {
    id: 6,
    title: "Macramé Aesthetics: Bohemian Knots in Modern Homes",
    excerpt: "How modern interior designers are incorporating textured natural cord hangings to introduce depth and tactile contrast to minimal urban settings.",
    category: "Community",
    categoryColor: "bg-surface-variant text-on-surface-variant",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBVHXmzcgHw7sulCDAb_2pVZHDasOElzMgfYOpkwSglKvHLinvzj21rdsPxypicwnizEKoPexJ1Na-T97ghRpVUopYErNtLhDfD45ZFF1QoglAMu-RCA0-EwCRFZhOcxaYxbPPhKFNBWJJiwjgBrk_B6kk51MBuGYYByp6sai-JomiSRwpZe6nt8MGn_9ZMr4eD4WdQXnXaD8SSKk_xpKDjhN-XmE4k8IC6LLJufKcsw3T7n2EOGjhw",
    date: "Jun 24, 2026",
    author: "Rohan Das",
    readTime: "5 min read"
  }
];

@Component({
  selector: 'app-blogs',
  standalone: true,
  imports: [CommonModule, RouterLink, FormsModule],
  templateUrl: './blogs.component.html'
})
export class BlogsComponent implements OnInit {
  categories = ["All Stories", "Crafting Tips", "Materials Guide", "Artisan Spotlight", "Community"];
  posts = signal<BlogPost[]>(ALL_POSTS);
  selectedCategory = signal<string>("All Stories");
  searchQuery = signal<string>("");

  ngOnInit(): void {
    if (typeof window !== 'undefined') {
      const customBlogs = localStorage.getItem('custom_blogs');
      if (customBlogs) {
        try {
          const parsed = JSON.parse(customBlogs);
          this.posts.set([...parsed, ...ALL_POSTS]);
        } catch {}
      }
    }
  }

  get filteredPosts(): BlogPost[] {
    const q = this.searchQuery().toLowerCase();
    const cat = this.selectedCategory();

    return this.posts().filter(post => {
      const matchesCategory = cat === "All Stories" || post.category === cat;
      const matchesSearch = post.title.toLowerCase().includes(q) || post.excerpt.toLowerCase().includes(q);
      return matchesCategory && matchesSearch;
    });
  }

  get featuredPost(): BlogPost {
    return this.posts()[0] || ALL_POSTS[0];
  }

  selectCategory(cat: string): void {
    this.selectedCategory.set(cat);
  }
}

<main class="min-h-screen bg-background text-on-background pt-8 pb-16 md:pt-12 md:pb-24">
  <div class="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop space-y-16">

    <!-- Filters and Search Bar -->
    <div class="flex flex-col md:flex-row gap-6 justify-between items-center border-b border-outline/15 pb-6">
      <div class="flex flex-wrap gap-2 justify-center md:justify-start w-full md:w-auto">
        @for (cat of categories; track cat) {
          <button
            (click)="selectCategory(cat)"
            class="px-4 py-2 font-label-md text-xs rounded-full transition-all duration-200"
            [class.bg-primary]="selectedCategory() === cat"
            [class.text-on-primary]="selectedCategory() === cat"
            [class.shadow-sm]="selectedCategory() === cat"
            [class.bg-surface-container-low]="selectedCategory() !== cat"
            [class.text-on-surface-variant]="selectedCategory() !== cat"
            [class.hover:bg-surface-container-high]="selectedCategory() !== cat">
            {{ cat }}
          </button>
        }
      </div>

      <div class="relative w-full md:w-80">
        <input
          type="text"
          placeholder="Search articles..."
          [ngModel]="searchQuery()"
          (ngModelChange)="searchQuery.set($event)"
          class="w-full bg-surface-container-lowest text-on-surface font-body-md text-sm pl-10 pr-4 py-3 rounded-full border border-outline/20 focus:outline-none focus:border-primary transition-colors"
        />
        <span class="material-symbols-outlined absolute left-3 top-3.5 text-on-surface-variant/65 text-sm select-none">
          search
        </span>
      </div>
    </div>

    <!-- Featured Post Card (Hero) -->
    @if (selectedCategory() === 'All Stories' && searchQuery() === '') {
      <div class="bg-surface-container-lowest rounded-2xl overflow-hidden organic-shadow grid grid-cols-1 lg:grid-cols-12 hover-lift">
        <div class="lg:col-span-7 h-[300px] lg:h-[450px] relative">
          <img
            [src]="featuredPost.image"
            [alt]="featuredPost.title"
            class="w-full h-full object-cover"
          />
        </div>
        <div class="lg:col-span-5 p-8 flex flex-col justify-center space-y-6">
          <div>
            <span class="inline-block px-3 py-1 rounded-full font-label-md text-xs {{ featuredPost.categoryColor }} mb-4">
              {{ featuredPost.category }}
            </span>
            <h2 class="font-headline-md text-2xl md:text-3xl text-on-surface hover:text-primary transition-colors leading-snug font-bold">
              <a [routerLink]="['/blogs', featuredPost.id]">
                {{ featuredPost.title }}
              </a>
            </h2>
          </div>
          <p class="font-body-md text-on-surface-variant text-sm leading-relaxed">
            {{ featuredPost.excerpt }}
          </p>
          <div class="flex items-center justify-between pt-4 border-t border-outline/10 text-xs font-body-md text-on-surface-variant/80">
            <span>{{ featuredPost.author }} • {{ featuredPost.date }}</span>
            <span class="text-primary font-label-md font-semibold">{{ featuredPost.readTime }}</span>
          </div>
        </div>
      </div>
    }

    <!-- Blogs Grid -->
    @if (filteredPosts.length > 0) {
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-gutter">
        @for (post of filteredPosts; track post.id) {
          <div class="bg-surface-container-lowest rounded-2xl overflow-hidden organic-shadow flex flex-col justify-between hover-lift group">
            <div>
              <div class="h-52 overflow-hidden relative">
                <img
                  [src]="post.image"
                  [alt]="post.title"
                  class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                />
              </div>
              <div class="p-6 space-y-4">
                <span class="inline-block px-3 py-0.5 rounded-full font-label-md text-[10px] {{ post.categoryColor }} uppercase tracking-wider font-semibold">
                  {{ post.category }}
                </span>
                <h3 class="font-headline-sm text-lg text-on-surface group-hover:text-primary transition-colors leading-snug line-clamp-2 font-bold">
                  <a [routerLink]="['/blogs', post.id]">
                    {{ post.title }}
                  </a>
                </h3>
                <p class="font-body-md text-xs text-on-surface-variant leading-relaxed line-clamp-3">
                  {{ post.excerpt }}
                </p>
              </div>
            </div>
            <div class="px-6 pb-6 pt-4 border-t border-outline/5 flex items-center justify-between text-[11px] font-body-md text-on-surface-variant/80">
              <span>By {{ post.author }} • {{ post.date }}</span>
              <span class="text-primary font-label-md font-semibold">{{ post.readTime }}</span>
            </div>
          </div>
        }
      </div>
    } @else {
      <div class="text-center py-20 bg-surface-container-low rounded-2xl space-y-4">
        <span class="material-symbols-outlined text-outline text-5xl">search_off</span>
        <h3 class="font-headline-sm text-lg text-on-surface font-bold">No articles found</h3>
        <p class="font-body-md text-sm text-on-surface-variant max-w-sm mx-auto">
          Try adjusting your filters or search keywords to find what you are looking for.
        </p>
      </div>
    }

    <!-- Newsletter Box -->
    <section class="bg-surface-container rounded-2xl p-8 md:p-12 flex flex-col lg:flex-row items-center justify-between gap-8 organic-shadow">
      <div class="space-y-3 max-w-lg text-center lg:text-left">
        <h3 class="font-display-lg text-2xl text-on-surface font-bold">Join the Atelier Circle</h3>
        <p class="font-body-md text-sm text-on-surface-variant">
          Receive a monthly dispatch containing craft blueprints, historical deep dives, and early alerts for enrollment openings.
        </p>
      </div>
      <div class="flex flex-col sm:flex-row gap-3 w-full lg:w-auto">
        <input
          type="email"
          placeholder="Enter your email"
          class="bg-surface-container-lowest text-on-surface font-body-md text-sm px-6 py-4 rounded-lg border border-outline/25 focus:outline-none focus:border-primary w-full sm:w-80"
        />
        <button class="bg-primary text-on-primary font-label-md text-sm px-8 py-4 rounded-lg hover:opacity-90 transition-opacity whitespace-nowrap font-semibold">
          Subscribe
        </button>
      </div>
    </section>

  </div>
</main>
